defaults: &defaults
  TWITTER_CONSUMER_KEY: YOUR_TWITTER_CONSUMER_KEY
  TWITTER_CONSUMER_SECRET: YOUR_TWITTER_CONSUMER_SECRET

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  S3_BUCKET: YOUR_S3_BUCKET
  AWS_ACCESS_KEY_ID: YOUR_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY
